name: CI

on:
  push:
    tags:
      - '*'

jobs:

  release:

    runs-on: ubuntu-18.04


    steps:

    - uses: actions/checkout@v2
      
    - name: Use Java8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8

    - name: Build debug apk
      run: ./gradlew clean assembleDebug
    
    - name: Create release and upload apk
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: app/build/outputs/apk/dev/debug/app-dev-debug.apk
        asset_name: cloxie-connect.apk
        tag: ${{ github.ref }}
        overwrite: true
